/* FILENAME: UNITS.H
 * PROGRAMMER: AS4
 * PURPOSE: Globe project declaration module.
 * LAST UPDATE: 07.06.2014
 */

#ifndef __UNITS_H_
#define __UNITS_H_

#include "anim.h"

/* Функция создания объекта анимации */
as4UNIT * AS4_CowUnitCreate( VOID );

/* Функция создания информационного объекта анимации */
as4UNIT * AS4_InfoUnitCreate( VOID );

as4UNIT * AS4_ClockUnitCreate( VOID );

as4UNIT * AS4_LogoUnitCreate( VOID );

as4UNIT * AS4_CubeUnitCreate( VOID );

#endif /* __UNITS_H_ 143 82*/

/* END OF 'UNITS.H' FILE */
